"""add_skills_evolution_tables

Revision ID: 3e5fc8d5167c
Revises: 4de6ececf227
Create Date: 2026-05-05 13:32:49.710689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5fc8d5167c'
down_revision: Union[str, Sequence[str], None] = '4de6ececf227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_local_state_key'), 'local_state', ['key'], unique=False)
    op.add_column('peers', sa.Column('skills_matrix', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peers', 'skills_matrix')
    op.drop_index(op.f('ix_local_state_key'), table_name='local_state')
    op.drop_table('local_state')
    # ### end Alembic commands ###
