"""Add PerformanceSnapshot table

Revision ID: 4c98f0d21f16
Revises: be79d91ded3d
Create Date: 2026-04-16 21:59:56.363353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c98f0d21f16'
down_revision: Union[str, Sequence[str], None] = 'be79d91ded3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_id'), 'performance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_node_id'), 'performance_snapshots', ['node_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_timestamp'), 'performance_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_snapshots_timestamp'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_node_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    # ### end Alembic commands ###
