"""add governance fields to tasks

Revision ID: 7d7f651f4e18
Revises: 70d880b989e4
Create Date: 2026-03-31 22:14:59.712646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7f651f4e18'
down_revision: Union[str, Sequence[str], None] = '70d880b989e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('requires_approval', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'approval_status')
    op.drop_column('tasks', 'requires_approval')
    # ### end Alembic commands ###
