"""add_performance_to_peerentry

Revision ID: be79d91ded3d
Revises: d336856c3e56
Create Date: 2026-04-16 06:10:01.650602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be79d91ded3d'
down_revision: Union[str, Sequence[str], None] = 'd336856c3e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('performance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peers', 'performance')
    # ### end Alembic commands ###
