"""Add decomposition_depth to TaskEntry

Revision ID: bf2d1d2ad2f2
Revises: c60379899840
Create Date: 2026-05-06 08:08:00.255947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2d1d2ad2f2'
down_revision: Union[str, Sequence[str], None] = 'c60379899840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('decomposition_depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'decomposition_depth')
    # ### end Alembic commands ###
