"""add_next_retry_at_to_tasks

Revision ID: cb55ff5ecf9a
Revises: 3e5fc8d5167c
Create Date: 2026-05-05 15:58:58.921647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb55ff5ecf9a'
down_revision: Union[str, Sequence[str], None] = '3e5fc8d5167c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_retry_at')
    # ### end Alembic commands ###
