"""add_advanced_consensus_fields_to_tasks

Revision ID: cffaf6555893
Revises: cb55ff5ecf9a
Create Date: 2026-05-05 19:34:43.164876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffaf6555893'
down_revision: Union[str, Sequence[str], None] = 'cb55ff5ecf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('consensus_strategy', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('quorum_threshold', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('results_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'results_metadata')
    op.drop_column('tasks', 'quorum_threshold')
    op.drop_column('tasks', 'consensus_strategy')
    # ### end Alembic commands ###
