"""Add strategies to PeerEntry

Revision ID: d336856c3e56
Revises: d3982625a266
Create Date: 2026-04-05 11:06:46.624224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd336856c3e56'
down_revision: Union[str, Sequence[str], None] = 'd3982625a266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('strategies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peers', 'strategies')
    # ### end Alembic commands ###
