"""add_consensus_fields_to_tasks

Revision ID: d3982625a266
Revises: 7d7f651f4e18
Create Date: 2026-03-31 23:43:18.964610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3982625a266'
down_revision: Union[str, Sequence[str], None] = '7d7f651f4e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('requires_consensus', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('min_votes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('results_votes', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('consensus_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'consensus_status')
    op.drop_column('tasks', 'results_votes')
    op.drop_column('tasks', 'min_votes')
    op.drop_column('tasks', 'requires_consensus')
    # ### end Alembic commands ###
